#! /bin/bash

echo -e "${column1_background_my}${column1_font_color_my}HOSTNAME        ${DEFAULT} = ${column2_font_color_my}${column2_background_my}$HOSTNAME${DEFAULT}"
echo -e "${column1_background_my}${column1_font_color_my}TIMEZONE        ${DEFAULT} = ${column2_background_my}${column2_font_color_my}$TIMEZONE${DEFAULT}"
echo -e "${column1_background_my}${column1_font_color_my}USER            ${DEFAULT} = ${column2_background_my}${column2_font_color_my}$USER${DEFAULT}"
echo -e "${column1_background_my}${column1_font_color_my}OS              ${DEFAULT} = ${column2_background_my}${column2_font_color_my}$OS${DEFAULT}"
echo -e "${column1_background_my}${column1_font_color_my}DATE            ${DEFAULT} = ${column2_background_my}${column2_font_color_my}$DATE${DEFAULT}"
echo -e "${column1_background_my}${column1_font_color_my}UPTIME          ${DEFAULT} = ${column2_background_my}${column2_font_color_my}$UPTIME${DEFAULT}"
echo -e "${column1_background_my}${column1_font_color_my}UPTIME_SEC      ${DEFAULT} = ${column2_background_my}${column2_font_color_my}$UPTIME_SEC${DEFAULT}"
echo -e "${column1_background_my}${column1_font_color_my}IP              ${DEFAULT} = ${column2_background_my}${column2_font_color_my}$IP${DEFAULT}"
echo -e "${column1_background_my}${column1_font_color_my}MASK            ${DEFAULT} = ${column2_background_my}${column2_font_color_my}$MASK${DEFAULT}"
echo -e "${column1_background_my}${column1_font_color_my}GATEWAY         ${DEFAULT} = ${column2_background_my}${column2_font_color_my}$GATEWAY${DEFAULT}"
echo -e "${column1_background_my}${column1_font_color_my}RAM_TOTAL       ${DEFAULT} = ${column2_background_my}${column2_font_color_my}$RAM_TOTAL GB${DEFAULT}"
echo -e "${column1_background_my}${column1_font_color_my}RAM_USED        ${DEFAULT} = ${column2_background_my}${column2_font_color_my}$RAM_USED GB${DEFAULT}"
echo -e "${column1_background_my}${column1_font_color_my}RAM_FREE        ${DEFAULT} = ${column2_background_my}${column2_font_color_my}$RAM_FREE GB${DEFAULT}"
echo -e "${column1_background_my}${column1_font_color_my}SPACE_ROOT      ${DEFAULT} = ${column2_background_my}${column2_font_color_my}$SPACE_ROOT MB${DEFAULT}"
echo -e "${column1_background_my}${column1_font_color_my}SPACE_ROOT_USED ${DEFAULT} = ${column2_background_my}${column2_font_color_my}$SPACE_ROOT_USED MB${DEFAULT}"
echo -e "${column1_background_my}${column1_font_color_my}SPACE_ROOT_FREE ${DEFAULT} = ${column2_background_my}${column2_font_color_my}$SPACE_ROOT_FREE MB${DEFAULT}"
echo ""
echo "Column 1 background = $column1_back ($color1)"
echo "Column 1 font color = $column1_font ($color2)"
echo "Column 2 background = $column2_back ($color3)"
echo "Column 2 font color = $column2_font ($color4)"
