version: '3'

services:
    
    server:
        build: ./part5/
    
    proxy-nginx:
        image: nginx
        ports:
            - 80:8080
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
