#! /bin/bash

echo -e "${column1_background}${column1_font_color}HOSTNAME        ${OFF} = ${column2_font_color}${column2_background}$HOSTNAME${OFF}"
echo -e "${column1_background}${column1_font_color}HOSTNAME        ${DEFAULT} = ${column2_background}${column2_font_color}$HOSTNAME${DEFAULT}"
echo -e "${column1_background}${column1_font_color}TIMEZONE        ${DEFAULT} = ${column2_background}${column2_font_color}$TIMEZONE${DEFAULT}"
echo -e "${column1_background}${column1_font_color}USER            ${DEFAULT} = ${column2_background}${column2_font_color}$USER${DEFAULT}"
echo -e "${column1_background}${column1_font_color}OS              ${DEFAULT} = ${column2_background}${column2_font_color}$OS${DEFAULT}"
echo -e "${column1_background}${column1_font_color}DATE            ${DEFAULT} = ${column2_background}${column2_font_color}$DATE${DEFAULT}"
echo -e "${column1_background}${column1_font_color}UPTIME          ${DEFAULT} = ${column2_background}${column2_font_color}$UPTIME${DEFAULT}"
echo -e "${column1_background}${column1_font_color}UPTIME_SEC      ${DEFAULT} = ${column2_background}${column2_font_color}$UPTIME_SEC${DEFAULT}"
echo -e "${column1_background}${column1_font_color}IP              ${DEFAULT} = ${column2_background}${column2_font_color}$IP${DEFAULT}"
echo -e "${column1_background}${column1_font_color}MASK            ${DEFAULT} = ${column2_background}${column2_font_color}$MASK${DEFAULT}"
echo -e "${column1_background}${column1_font_color}GATEWAY         ${DEFAULT} = ${column2_background}${column2_font_color}$GATEWAY${DEFAULT}"
echo -e "${column1_background}${column1_font_color}RAM_TOTAL       ${DEFAULT} = ${column2_background}${column2_font_color}$RAM_TOTAL GB${DEFAULT}"
echo -e "${column1_background}${column1_font_color}RAM_USED        ${DEFAULT} = ${column2_background}${column2_font_color}$RAM_USED GB${DEFAULT}"
echo -e "${column1_background}${column1_font_color}RAM_FREE        ${DEFAULT} = ${column2_background}${column2_font_color}$RAM_FREE GB${DEFAULT}"
echo -e "${column1_background}${column1_font_color}SPACE_ROOT      ${DEFAULT} = ${column2_background}${column2_font_color}$SPACE_ROOT MB${DEFAULT}"
echo -e "${column1_background}${column1_font_color}SPACE_ROOT_USED ${DEFAULT} = ${column2_background}${column2_font_color}$SPACE_ROOT_USED MB${DEFAULT}"
echo -e "${column1_background}${column1_font_color}SPACE_ROOT_FREE ${DEFAULT} = ${column2_background}${column2_font_color}$SPACE_ROOT_FREE MB${DEFAULT}"
